// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofcchocnplwpfalqlvnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mY2Nob2NucGx3cGZhbHFsdm52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNDgyODMsImV4cCI6MjA2NDkyNDI4M30.gLm-W675zAHZlQSje5PtyWuhdfTq17TpMg54zcjlcrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);